name: publish

on:
  push:
    tags:
      - 'v*'

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
  GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}

jobs:
  publish-windows:
    runs-on: windows-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Build
      - run: CALL gradlew.bat linkReleaseSharedMingwX64
        shell: cmd
      - run: CALL gradlew.bat linkReleaseSharedMingwX86
        shell: cmd

      # Upload decsync.dll
      - uses: actions/upload-artifact@v2
        with:
          name: decsync_x64.dll
          path: build/bin/mingwX64/releaseShared/decsync.dll
      - uses: actions/upload-artifact@v2
        with:
          name: decsync_x86.dll
          path: build/bin/mingwX86/releaseShared/decsync.dll

      # Setup signing and publish
      - run: CALL echo %GPG_KEY_CONTENTS% > %SIGNING_SECRET_KEY_RING_FILE%.base64 && CALL certutil -decode %SIGNING_SECRET_KEY_RING_FILE%.base64 %SIGNING_SECRET_KEY_RING_FILE% && CALL gradlew.bat publishMingwX64PublicationToMavenRepository
        shell: cmd
  publish-macos:
    runs-on: macos-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Build
      - run: ./gradlew linkReleaseSharedMacosX64
      - run: ./gradlew linkReleaseSharedMacosArm64

      # Upload
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync_amd64.dylib
          path: build/bin/macosX64/releaseShared/libdecsync.dylib
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync_arm64.dylib
          path: build/bin/macosArm64/releaseShared/libdecsync.dylib
  publish-linux-and-misc:
    needs: [publish-windows, publish-macos]
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Build
      - run: ./gradlew linkReleaseSharedLinuxX64
      - run: ./gradlew linkReleaseSharedLinuxArm64
      - run: ./gradlew linkReleaseSharedLinuxArm32Hfp

      # Upload libdecsync.so
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync_amd64.so
          path: build/bin/linuxX64/releaseShared/libdecsync.so
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync_arm64.so
          path: build/bin/linuxArm64/releaseShared/libdecsync.so
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync_arm32.so
          path: build/bin/linuxArm32Hfp/releaseShared/libdecsync.so

      # Create and upload libdecsync.deb
      - run: ./create-deb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: libdecsync.deb
          path: libdecsync.deb

      # Setup signing and publish
      - run: echo "$GPG_KEY_CONTENTS" | base64 -d > "$SIGNING_SECRET_KEY_RING_FILE" && ./gradlew publish